site_name: liftConfig
site_author: Tim Howlinson

theme:
  name: material
  features:
    - content.code.annotation
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - search.suggest
    - search.highlight
    - navigation.expand
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    # - toc.integrate
    - toc.follow
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off
        name: Switch to Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to Dark Mode
  icon:
    logo: simple/googlecontaineroptimizedos

nav:
  - Blog:
    - blog/index.md
  - Reference:
    - Networking:
      - Cisco IOS-XR: networking/iosxr.md
      - FortiOS: networking/fortinet.md
      - VMware NSX-T: networking/nsxt.md
    - IaC:
      - Terraform Associate: iac/terraform-associate.md
  - About: 
    - About Me: about/about-me.md
    - Office Setup: about/office-setup.md
  - Tags: tags.md

plugins:
  - search:
      lang: en
  - tags:
      tags_file: tags.md
  - blog:
      categories: true 
      categories_name: Categories
      categories_allowed:
        - networking
        - cloud
        - coding
        - IaC
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/timhowlinson
    - icon: fontawesome/brands/github-alt
      link: https://github.com/liftconfig
    - icon: fontawesome/solid/envelope
      link: mailto:tim.howlinson@gmail.com
    - icon: fontawesome/solid/dumbbell
      link: https://www.openpowerlifting.org/u/timhowlinson
  generator: false
  analytics:
    provider: google
    property: G-C3VKY555NW

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - toc:
      permalink: true

copyright: |
  &copy; 2024 liftConfig





